### PR TITLE
 Fix issues with x mesh definition and usage

### PR DESCRIPTION
**Pull request by ilario**
See discussion on #12

### CODE REVIEW

**Comment by ilario** [comment]
@barnesgroupICL in the comments above I can't see the point in the code they refer to...

**Comment by ilario** [comment]
@barnesgroupICL can you explicit which were the problematic bits?

I tested how much residual current pinAna outputs from a halved (using asymmetricize from #4) symmetric solution (with ions and surface recombination) under 1 sun (in theory there should be zero, I suppose that a "bad" current estimation will get quite far from zero).

With all the code from this PR (and my pinParams, which differs in some parts form the one in this repository, but not by much, intrinsic thickness is 500 nm, SRH times 5e-10): -0.069 mA/cm2

Without all this PR (and my pinParams): -1.96 mA/cm2

Maybe there's some better way to fix this?
I think that the current way of calculating the current is quite good and has little noise.

Regarding the part I commented out in the pindrift about generation in 3f5726c, I thought it was not needed but now I got the point from the comment, I'm going to fix the commit.

Should I revert also the addition to meshgen_x in 32f3439 (as seems that the alternative mitigation via ismembertol in pinAna in 97b7c62 is enough)?
It is not needed but can reduce the probability of having this kind of problems (inclusion or exclusion of single points on the border when using inequalities) in the future.

**Comment by barnesgroupICL** [comment]
Morning!

When you discuss residual current – am I right in assuming that you mean that you find the Voc using the symmetricised (open circuit) model then applied that voltage in the asymmetricised (closed circuit) then look at the current?

I think I’ve mentioned before that there may be some small difference in the Voc you get from open and closed circuit boundary conditions. In which case the higher residual current could be correct since the Voc obtained from the symmetricised solution may be too low. So I’m not sure this is a good way to test whether the PR is giving you a better solution. The size of the current at equilibrium would be a better test since we know this should be zero.

Maybe there's some better way to fix this?

It would be better to use the findVoc function with the closed conditions and avoid using the Voc from the open circuit conditions.

I think that the current way of calculating the current is quite good and has little noise.

What is the ‘current’ way that you’re using to calculate the current – way it the method from the continuity equations? The method using flux boundary conditions is certainly more reliable at high applied potentials. I think I can fix the continuity equation method but it will require some attention.

Regarding the part I commented out in the pindrift about generation in 3f5726c<https://github.com/barnesgroupICL/Driftfusion/commit/3f5726c86998192b048f0b713cebcd4be1b09ca6>, I thought it was not needed but now I got the point from the comment, I'm going to fix the commit.

Ok cool.

Should I revert also the addition to meshgen_x in 32f3439<https://github.com/barnesgroupICL/Driftfusion/commit/32f3439ccaec0619fd2da8d69a28d510cf0530cf> (as seems that the alternative mitigation via ismembertol in pinAna in 97b7c62<https://github.com/barnesgroupICL/Driftfusion/commit/97b7c62f15ec29ced2893197232d10a70e2ec537> is enough)?

I’m still not sure about the idea of having the interface points as half of one material and half the other- do you have a good rationale for this or is it based on the residual current analysis that you discussed?

Best,


Phil

**Comment by ilario** [comment]
> When you discuss residual current – am I right in assuming that you mean that you find the Voc using the symmetricised (open circuit) model then applied that voltage in the asymmetricised (closed circuit) then look at the current?

Yess

> I think I’ve mentioned before that there may be some small difference in the Voc you get from open and closed circuit boundary conditions. In which case the higher residual current could be correct since the Voc obtained from the symmetricised solution may be too low. So I’m not sure this is a good way to test whether the PR is giving you a better solution. The size of the current at equilibrium would be a better test since we know this should be zero.

Okk

>> Maybe there's some better way to fix this?

> It would be better to use the findVoc function with the closed conditions and avoid using the Voc from the open circuit conditions.

Sure it is also needed :) I added another version of findVoc in #15.

>> I think that the current way of calculating the current is quite good and has little noise.

> What is the ‘current’ way that you’re using to calculate the current – way it the method from the continuity equations? The method using flux boundary conditions is certainly more reliable at high applied potentials. I think I can fix the continuity equation method but it will require some attention.

Yes, I'm using the way using the continuity equations and I did not get big troubles with it.

>> Should I revert also the addition to meshgen_x in 32f3439<https://github.com/barnesgroupICL/Driftfusion/commit/32f3439ccaec0619fd2da8d69a28d510cf0530cf> (as seems that the alternative mitigation via ismembertol in pinAna in 97b7c62<https://github.com/barnesgroupICL/Driftfusion/commit/97b7c62f15ec29ced2893197232d10a70e2ec537> is enough)?

> I’m still not sure about the idea of having the interface points as half of one material and half the other- do you have a good rationale for this or is it based on the residual current analysis that you discussed?

Let's take the example of the generation profile (just because it's an easy one (so easy that in the generation case just a multiplication is better), but the same concept applies to recombination), the current integrated profile (when calculating the current with the continuity equations method) can be represented like this:

BM

which overestimates the generation area.
My ugly fix of putting half of the point in each interface can be represented like this:

BM05

Anyway **I'm preparing a new PR with a better solution**: eliminate binary matrices and use trapz integral over each layer separately. Using trapz the integral ends exactely where the layer ends (if the last point is effectively matched, e.g. using ismembertol) can be represented like this:

trapz

So I'm going to close this one PR, even if just the part of pinAna will be different in the next PR.

**Comment by ilario** [comment]
Annoyingly I just found a condition where the J calculation seems to be troublesome:
When calculating the current with 0.001 sun illumination I expected a negative current (like what I have with the higher illuminations I tested, from 0.001 to 1 sun) but I had:

* including this PR (or the trapz based variant): 0.0092 mA/cm2
* without this PR: 0.0039 mA/cm2
* with the legacy method included [in v1.0](https://github.com/barnesgroupICL/Driftfusion/blob/master/Driftfusion%20v1.0/pinAna.m#L152-L196): -0.0117 mA/cm2 which is more reasonable

**Comment by barnesgroupICL** [comment]
Have you tried it with the new Bcs (boundary conditions) that I sent to you?

**Comment by barnesgroupICL** [comment]
Let's take the example of the generation profile (just because it's an easy one (so easy that in the generation case just a multiplication is better), but the same concept applies to recombination), the current integrated profile (when calculating the current with the continuity equations method) can be represented like this:

[BM]<https://camo.githubusercontent.com/282dab0d0d7d4e424d9a251caa913d20376ffc57/68747470733a2f2f692e696d6775722e636f6d2f637577366734392e706e67>

which overestimates the generation area.
My ugly fix of putting half of the point in each interface can be represented like this:

[BM05]<https://camo.githubusercontent.com/0a40620d3c5eec8fc126a4c5facc8b4929e4a0e6/68747470733a2f2f692e696d6775722e636f6d2f454b7075347a702e706e67>

I can’t see the difference between these two cases particularly in terms of overestimation? Using a finer mesh here would also improve accuracy.


Anyway I'm preparing a new PR with a better solution: eliminate binary matrices and use trapz integral over each layer separately. Using trapz the integral ends exactely where the layer ends (if the last point is effectively matched, e.g. using ismembertol) can be represented like this:

[trapz]<https://camo.githubusercontent.com/3c35cffc29566a1a9cb7c6915a285e8a334818e1/68747470733a2f2f692e696d6775722e636f6d2f36476a44614c6e2e706e67>

So I'm going to close this one PR, even if just the part of pinAna will be different in the next PR.

This looks good but I haven’t looked at it in detail…

**Pull request closed without merging**
