### PR TITLE
Repeat changes from PR #39 "dfpde faster execution"

### PR DESCRIPTION
**Pull request by ilario**
The only difference from #39 is the `otherwise` => `case 0` change requested here https://github.com/barnesgroupICL/Driftfusion/pull/39#pullrequestreview-451083993.

### CODE REVIEW

**Comment by ilario** [comment]
I just tested on R2018a on Windows and, only on Windows, it does not work!
The problem is this `==` comparison between doubles, which on Linux (and on macOS, right @barnesgroupICL?) works but on Windows does not:

https://github.com/ilario/Driftfusion/blob/cae3cda50acedae3d8469a8aefbdcc5aa5850ae3/Core/df.m#L223

So, on Linux the two doubles are always identical, while on Windows for some reason the last bit can be different. Maybe this part (which is one of the slowest of the entire block) has to be restored as it was or we have to use ismembertol or ismembc2 or builtin _ismemberhelper.

**Comment by ilario** [comment]
...or we have to cast everything to a single, which sounds like a good idea and I just tested it works :D

**Comment by ilario** [comment]
I just observed the same behaviour on Linux also, no idea at which point I included something causing this. Anyway the solution casting the x position to a single works and I added a commit including it.

**Comment by barnesgroupICL** [comment]
Thanks for all the testing on different OS. Makes no sense to me that the inequalities work on some and not on others...

**Comment by ilario** [comment]
Yep, sorry, finally it was not due to the OS but due to some of the other many changes I did in some of the other pull requests.

**Comment by barnesgroupICL** [comment]
This PR also had changes to the dfpde subfunction which led a merge conflict. Presumably these are changes to improve the code efficiency. Please let me know if there were any bug fixes within that? For the time being I have not accepted the changes to the dfpde as I felt it makes it less accessible.

**Comment by ilario** [comment]
I just checked the PR content and got broken with the commit https://github.com/barnesgroupICL/Driftfusion/pull/64/commits/fef125cbd66f0420732ee3ad59b52bdb94b0eca0

Anyway, no it does not fix any bug, it's just the fastest possible way I found to run dfpde (which is the heaviest component in the simulation), see the discussion on #39.

I agree that it makes the code less readable. Maybe some of the changes decrease the execution time without affecting any DF equation, but I did not remember which.

**Comment by ilario** [comment]
As this is very outdated, let's close this and discuss on #73

**Pull request closed without merging**
